### ISSUE TITLE
Points calculation incorrect if method names in public and secret junit class are equal.

### ISSUE THREAD

**Issue by meisterT** [FAU-Inf2/AuDoscore#26]
Points calculation uses points from public test instead of specific method.

**Comment by cubu1337** [comment]
Hi Tobi,

> On 24 Apr 2015, at 09:39, Tobias Werth <notifications@github.com> wrote:
> 
> Points calculation uses points from public test instead of specific method.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/FAU-Inf2/AuDoscore/issues/26>.
> 
Oh ein Bug.
Ich werde mich so schnell wie möglich darum kümmern(Ist ja was kritisches). Das wird noch vor 15 Uhr gefixt.

Gruss,
Cuong

**Comment by cubu1337** [comment]
Fixed with a5a8cc6baf1dd5de6a2f2bd651756cf6326f2ae8
